services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
      dockerfile: Dockerfile
    env_file:
      - ./services/reverse-proxy/.env
    volumes:
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/proxy_params.conf
        target: /etc/nginx/proxy_params.conf
    ports:
      - 8080:80
    depends_on:
      files:
        condition: service_healthy
  files:
    build:
      context: ./services/files
      target: dev
    volumes:
      - ./services/files/cmd:/usr/src/app/cmd
      - ./services/files/internal:/usr/src/app/internal
    env_file:
      - ./services/files/.env
    healthcheck:
      test: ['CMD', './healthcheck']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
