services:
  files:
    build:
      context: ./services/files
      target: dev
    volumes:
      - ./services/files/cmd:/usr/src/app/cmd
      - ./services/files/internal:/usr/src/app/internal
    env_file:
      - ./services/files/.env
    ports:
      - 3000:3000
